name: Build and Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml
  
  build:
    needs:
      - build-docs
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
          {
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}'
            echo keyPassword='${{ secrets.KEY_PASSWORD }}'
            echo keyAlias='${{ secrets.KEY_ALIAS }}'
            echo storeFile='../keystore.jks'
          } > keystore.properties
          echo '${{ secrets.KEYSTORE }}' | base64 -d > keystore.jks
        fi

    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Move artifact to assets
      run: |
          cd ./github-pages
          tar xvf artifact.tar && rm artifact.tar
          cd ../
          mkdir ./app/src/main/assets
          mv ./github-pages ./app/src/main/assets/XtMapper-docs

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
        
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          app/build/outputs/apk/release/*.apk
         
